services:
  # MongoDB
  mongodb:
    image: mongo:4.4
    container_name: sistema_eventos_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sistema_eventos
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Aplicação principal (Backend + Frontend Simples)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema_eventos_app
    restart: unless-stopped
    ports:
      - "8000:8000"  # Backend Django
      - "8080:8080"  # Frontend Simples
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - DB_NAME=sistema_eventos
      - SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080,http://0.0.0.0:8080
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./logs:/app/backend/logs
    networks:
      - app-network
    command: ["bash", "/app/start.sh"]

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge 